### ISSUE TITLE
description

### ISSUE THREAD

**Issue by uccasco** [CoxGroup/slab-dl-monte#1]
I think it's helpful to add a few words so people know what's going on.

In GCMC, the volume enters the acceptance criteria for insertions [stuff/vol] and deletions [vol*(other stuff)]. In the original implementation, they tried to make things more efficient by only inserting into the slab region (where moves are likely to be accepted). This has the consequence of effectively reducing the volume of the system, but this was not accounted for in the acceptance criteria. The had a knock-on effect of (effectively) changing the fugacity of the system, so the densities inside the slit did not correspond to their bulk values.

**Comment by annatbui** [comment]
Yes, I can add these points (I will try to add a plot somewhere too). I guess the best fix for this would actually be to change the acceptance criteria, which then will maintain the efficiency.

**Comment by uccasco** [comment]
yeah, I thought that. I wonder whether or not it's worth the extra if statement though...
